<?php

namespace App\Tests;

use App\Entity\MovieTime;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class BookingsControllerTest extends WebTestCase
{
    private $client;
    /**
     * @var EntityManager
     */
    private $em;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = static::createClient();
        $userRepository = static::$container->get(UserRepository::class);
        static::$kernel = static::createKernel();
        static::$kernel->boot();
        $this->em = static::$kernel->getContainer()
            ->get('doctrine')->getManager();

        // retrieve the test user
        $testUser = $userRepository->findOneByEmail('likho@gmail.com');

        // simulate $testUser being logged in
        $this->client->loginUser($testUser);
    }

    public function testIndex()
    {
        $this->client->request('GET', '/bookings');
        $this->assertResponseIsSuccessful();
        $this->assertSelectorTextContains('h2', 'Manage bookings');
    }

    public function testCreateBookingPage()
    {
        $movieTimes = $this->em
            ->getRepository(MovieTime::class)
            ->findAll();

        $this->client->request('GET', "/bookings/create/{$movieTimes[0]->getId()}");
        $this->assertResponseIsSuccessful();
        $this->assertSelectorTextContains('label', 'How many tickets would you like??');
    }

    protected function tearDown(): void
    {
        parent::tearDown();
        $this->em->close();
        $this->em = null;
    }
}