index:
    path: /
    controller: App\Controller\MoviesController::index
view:
    path: /movie/{movie}
    controller: App\Controller\MoviesController::view
make-booking:
    path: /bookings/create/{movieTime}
    controller: App\Controller\BookingsController::create
bookings:
    path: /bookings
    controller: App\Controller\BookingsController::index
create-booking:
    path: /bookings/add/{movieTime}
    controller: App\Controller\BookingsController::add
cancel-booking:
    path: /bookings/cancel/{booking}
    controller: App\Controller\BookingsController::cancel